[[headers]]
  # Определяем заголовки для всех файлов
  for = "/*"
    [headers.values]
    # Разрешаем кросс-доменные запросы
    Access-Control-Allow-Origin = "*"

# Перенаправление всех маршрутов на index.html для SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200